"""
StructureGenerator — generate an idiomatic project structure for
the modernised repository.

Given the repo philosophy and target language, outputs a clean directory
layout and a ``file_mapping.json`` mapping original → new file paths.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Data classes
# ------------------------------------------------------------------

@dataclass
class GeneratedStructure:
    """Result of structure generation."""
    target_language: str = ""
    directories: list[str] = field(default_factory=list)
    file_mapping: dict[str, str] = field(default_factory=dict)
    generated_files: dict[str, str] = field(default_factory=dict)  # path → content


# ------------------------------------------------------------------
# Templates
# ------------------------------------------------------------------

PYTHON_STRUCTURE = {
    "dirs": ["src", "src/models", "src/services", "src/utils", "tests", "docs"],
    "files": {
        "src/__init__.py": '"""Modernised codebase — auto-generated by Legacy Modernizer."""\n',
        "src/models/__init__.py": "",
        "src/services/__init__.py": "",
        "src/utils/__init__.py": "",
        "tests/__init__.py": "",
        "pyproject.toml": (
            '[project]\nname = "modernised-repo"\nversion = "1.0.0"\n'
            'requires-python = ">=3.9"\n\n'
            '[tool.pytest.ini_options]\ntestpaths = ["tests"]\n'
        ),
        ".env.example": "# Environment variables for the modernised repository\n",
    },
}

GO_STRUCTURE = {
    "dirs": ["cmd", "internal", "internal/models", "internal/services", "pkg", "docs"],
    "files": {
        "go.mod": 'module modernised-repo\n\ngo 1.21\n',
        "cmd/main.go": (
            'package main\n\nimport "fmt"\n\nfunc main() {\n'
            '\tfmt.Println("Modernised repository")\n}\n'
        ),
        ".env.example": "# Environment variables for the modernised repository\n",
    },
}


# ------------------------------------------------------------------
# Generator
# ------------------------------------------------------------------

class StructureGenerator:
    """Generate an idiomatic project structure for the target language."""

    def generate(
        self,
        target_language: str,
        original_files: list[str],
        philosophy: dict | None = None,
    ) -> GeneratedStructure:
        """
        Generate a project structure and file mapping.

        Args:
            target_language: Target language ("python" or "go").
            original_files: List of original file paths.
            philosophy: Optional repo philosophy dict for smarter mapping.
        """
        template = (
            PYTHON_STRUCTURE if target_language == "python"
            else GO_STRUCTURE
        )

        structure = GeneratedStructure(target_language=target_language)
        structure.directories = template["dirs"]
        structure.generated_files = dict(template["files"])

        # Map original files to new locations
        structure.file_mapping = self._map_files(
            original_files, target_language,
        )

        logger.info(
            "Generated %s structure: %d dirs, %d files mapped",
            target_language, len(structure.directories),
            len(structure.file_mapping),
        )
        return structure

    # ------------------------------------------------------------------
    # File mapping
    # ------------------------------------------------------------------

    def _map_files(
        self,
        original_files: list[str],
        target_language: str,
    ) -> dict[str, str]:
        """Map original file paths to idiomatic new paths."""
        mapping: dict[str, str] = {}
        ext = ".py" if target_language == "python" else ".go"
        src_dir = "src" if target_language == "python" else "internal"

        for orig_path in original_files:
            p = Path(orig_path)
            stem = p.stem.lower().replace("-", "_").replace(" ", "_")

            # Determine sub-directory based on filename heuristics
            sub_dir = self._classify_file(stem, p.suffix.lower())
            new_path = f"{src_dir}/{sub_dir}/{stem}{ext}" if sub_dir else f"{src_dir}/{stem}{ext}"
            mapping[orig_path] = new_path

        return mapping

    @staticmethod
    def _classify_file(stem: str, ext: str) -> str:
        """Classify a file into a subdirectory based on naming heuristics."""
        stem_lower = stem.lower()

        # Models / data
        if any(w in stem_lower for w in ("model", "entity", "schema", "record", "data")):
            return "models"

        # Services / business logic
        if any(w in stem_lower for w in ("service", "handler", "controller", "processor")):
            return "services"

        # Utilities
        if any(w in stem_lower for w in ("util", "helper", "common", "shared")):
            return "utils"

        # Default: root of src
        return ""

    def file_mapping_json(self, mapping: dict[str, str], indent: int = 2) -> str:
        """Serialize the file mapping to JSON."""
        return json.dumps(mapping, indent=indent)
