"""
DocGenerator — auto-generate documentation for the modernised repository.

Capabilities:
  1. **File-level docs**: Add docstrings/comments to translated code.
  2. **Repository README**: Generate a comprehensive README.md with architecture
     diagram (Mermaid), file map, data flow, setup, and more.
  3. **Workflow docs**: Generate WORKFLOW_{name}.md for each converted workflow.
"""

from __future__ import annotations

import json
import logging
from typing import Callable, Optional

logger = logging.getLogger(__name__)


class DocGenerator:
    """Generate documentation for the modernised repository."""

    def __init__(self, llm_fn: Optional[Callable[[str, str], str]] = None):
        """
        Args:
            llm_fn: Optional LLM callable(system_prompt, user_prompt) -> text.
                    If None, generates template-based docs without LLM.
        """
        self._llm_fn = llm_fn

    # ------------------------------------------------------------------
    # File-level documentation
    # ------------------------------------------------------------------

    def generate_file_docs(
        self,
        translated_code: str,
        file_path: str,
        source_language: str,
        target_language: str,
    ) -> str:
        """
        Add docstrings/comments to translated code.

        If LLM is available, uses it for richer documentation.
        Otherwise, adds a basic header comment.
        """
        if self._llm_fn:
            system = (
                "You are a documentation expert. Add comprehensive docstrings "
                "and inline comments to this code. Return ONLY the documented "
                "code (no JSON, no explanations)."
            )
            user = (
                f"Add documentation to this {target_language} code that was "
                f"translated from {source_language}.\n\n"
                f"File: {file_path}\n\n{translated_code}"
            )
            try:
                return self._llm_fn(system, user)
            except Exception as exc:
                logger.warning("LLM doc generation failed: %s", exc)

        # Fallback: add a basic header
        comment = "#" if target_language == "python" else "//"
        header = (
            f"{comment} Auto-generated by Legacy Modernizer\n"
            f"{comment} Original: {file_path} ({source_language})\n"
            f"{comment} Target: {target_language}\n\n"
        )
        return header + translated_code

    # ------------------------------------------------------------------
    # Repository README
    # ------------------------------------------------------------------

    def generate_readme(
        self,
        repo_philosophy: dict,
        file_mapping: dict[str, str],
        dependency_graph: dict,
        workflows: list[dict],
        target_language: str = "python",
    ) -> str:
        """
        Generate a comprehensive README.md for the modernised repository.

        Includes 9 sections per §4.2 of the upgrade brief.
        """
        sections = []

        # 1. Overview
        sections.append("# Modernised Repository\n")
        sections.append("> Auto-generated by Legacy Modernizer\n")

        pattern = repo_philosophy.get("architectural_pattern", "Unknown")
        data_flow = repo_philosophy.get("primary_data_flow", "Unknown")
        sections.append(f"## Overview\n")
        sections.append(f"**Architecture**: {pattern}\n")
        sections.append(f"**Data Flow**: {data_flow}\n")

        # 2. Architecture Diagram (Mermaid)
        sections.append("## Architecture\n")
        mermaid = self._generate_mermaid(dependency_graph)
        sections.append(f"```mermaid\n{mermaid}\n```\n")

        # 3. File Map
        sections.append("## File Map\n")
        sections.append("| Original | Modernised |")
        sections.append("|----------|-----------|")
        for orig, new in sorted(file_mapping.items()):
            sections.append(f"| `{orig}` | `{new}` |")
        sections.append("")

        # 4. Data Flow
        if data_flow and data_flow != "Unknown":
            sections.append("## Data Flow\n")
            sections.append(f"{data_flow}\n")

        # 5. Setup
        sections.append("## Setup\n")
        if target_language == "python":
            sections.append("```bash")
            sections.append("python -m venv .venv")
            sections.append("source .venv/bin/activate")
            sections.append("pip install -r requirements.txt")
            sections.append("```\n")
        else:
            sections.append("```bash")
            sections.append("go mod download")
            sections.append("go build ./...")
            sections.append("```\n")

        # 6. Environment Variables
        config = repo_philosophy.get("configuration_strategy", "")
        sections.append("## Environment Variables\n")
        sections.append("Copy `.env.example` to `.env` and fill in the required values.\n")
        if config:
            sections.append(f"Configuration strategy: {config}\n")

        # 7. Workflow Instructions
        if workflows:
            sections.append("## Workflows\n")
            for wf in workflows:
                if isinstance(wf, dict):
                    sections.append(
                        f"- **{wf.get('description', 'Workflow')}**: "
                        f"See `{wf.get('modern_file_path', 'N/A')}`"
                    )
            sections.append("")

        # 8. Testing
        sections.append("## Testing\n")
        if target_language == "python":
            sections.append("```bash\npython -m pytest tests/ -v\n```\n")
        else:
            sections.append("```bash\ngo test ./...\n```\n")

        # 9. Known Differences
        sections.append("## Known Differences from Original\n")
        sections.append("- File I/O operations have been modernised to use native APIs")
        sections.append("- COBOL data types mapped to Python/Go equivalents")
        sections.append("- JCL workflows converted to Python scripts")
        sections.append("- See individual file documentation for specific changes\n")

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # Workflow documentation
    # ------------------------------------------------------------------

    def generate_workflow_docs(
        self,
        workflows: list[dict],
    ) -> dict[str, str]:
        """
        Generate WORKFLOW_{name}.md for each converted workflow.

        Returns a dict of {filename: markdown_content}.
        """
        docs: dict[str, str] = {}

        for wf in workflows:
            if not isinstance(wf, dict):
                continue

            name = wf.get("description", "workflow").replace(" ", "_").lower()
            doc_name = f"WORKFLOW_{name}.md"

            lines = [
                f"# Workflow: {wf.get('description', 'Unknown')}\n",
                f"**Type**: {wf.get('workflow_type', 'unknown')}\n",
                f"**Source**: `{wf.get('source_file', 'N/A')}`\n",
                f"**Modernised file**: `{wf.get('modern_file_path', 'N/A')}`\n",
                "## Description\n",
                f"{wf.get('description', 'No description available.')}\n",
                "## How to Run\n",
                "```bash",
                f"python {wf.get('modern_file_path', 'workflow.py')}",
                "```\n",
            ]

            docs[doc_name] = "\n".join(lines)

        return docs

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _generate_mermaid(dependency_graph: dict) -> str:
        """Generate a Mermaid graph from the dependency graph."""
        lines = ["graph TD"]

        if not dependency_graph:
            lines.append("    A[No dependency data available]")
            return "\n".join(lines)

        # Create nodes and edges
        node_ids: dict[str, str] = {}
        counter = 0

        for file_path, data in dependency_graph.items():
            node_id = f"N{counter}"
            counter += 1
            # Clean path for display
            label = file_path.replace("/", "/\\n") if len(file_path) > 30 else file_path
            lang = data.get("language", "?") if isinstance(data, dict) else "?"
            lines.append(f'    {node_id}["{label}\\n({lang})"]')
            node_ids[file_path] = node_id

        for file_path, data in dependency_graph.items():
            if not isinstance(data, dict):
                continue
            source_id = node_ids.get(file_path, "")
            for edge in data.get("edges", []):
                target = edge.get("target", "")
                edge_type = edge.get("type", "")
                target_id = node_ids.get(target, "")
                if source_id and target_id:
                    lines.append(f"    {source_id} -->|{edge_type}| {target_id}")

        return "\n".join(lines)
